export const BADGE_LABELS = {
  recruiting:         '招募中',
  pending_activation: '待啟用',
  active:             '服務中',
  cancelled:          '已解散',
  full:               '已滿員',
  pending_confirmation: '成員填寫中',
  confirming:           '確認期中',
  disputed:             '申訴中',
  ended:              '已結束',
  paused:             '已暫停',
  closed:             '已關閉',
  approval:           '審核加入',
  pending:            '待確認',
  verified:           '已驗證',
  upcoming:           '即將續訂',
  member_joined:      '申請通過',
  active_renewal:     '即將續訂',
}
